---
# code: language=ansible
# Path: ansible/group_vars/all/lgtm.yml
# This file contains the variables for the OTEl LGTM service
# Open Telemetry - Loki Grafana Tempo Prometheus

lgtm_data_dir_name: svc_lgtm_data
lgtm_data_dir: "{{ docker_volumes_dir }}/{{ lgtm_data_dir_name }}"
lgtm_docker_image_name: grafana/otel-lgtm
lgtm_docker_image_version: latest
lgtm_docker_volume_name: svc_lgtm_data_volume
lgtm_port_A: "3000"
lgtm_port_B: "4317"
lgtm_port_C: "4318"
