---
# code: language=ansible
# Path: ansible/group_vars/all/portainer.yml
# This file contains the variables for the portainer service

portainer_data_dir_name: svc_portainer_data
portainer_data_dir: "{{ docker_volumes_dir }}/{{ portainer_data_dir_name }}"
portainer_docker_image_name: portainer/portainer-ce
portainer_docker_image_version: latest
portainer_docker_volume_name: svc_portainer_data_volume
portainer_port_A: "9000"
portainer_port_B: "9443"
portainer_port_C: "8000"
