---
# code: language=ansible
# Path: ansible/group_vars/rasp.yml
# This file contains the variables for the rasp host

# Variables for the Operator GPG service

deerhide_operator_home: "/home/deerhide-operator"
git_executable_path: "/usr/bin/git"
python_executable_path: "/usr/bin/python3"

# Operator GPG configuration
gpg_group: deerhide-operator
