---
# code: language=ansible

- name: Melissa's playbook
  hosts:
    - melissa
  roles:
    - role: svc_docker
    - role: svc_traefik
    - role: svc_coredns
    - role: svc_httpd
    - role: svc_haproxy
    - role: svc_nut
