---
# code: language=ansible
# Path: ansible/group_vars/nas/inventory.yml
# This file contains the inventory variables for the NAS hosts

# Inventory variables for the NAS hosts
ansible_port: 2222
ansible_python_interpreter: /usr/local/bin/python3.9
